export const dataOfPage4 = {
    "All": [
        {
            id: 6,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-1.png",
            job: "Software Engineer",
            companyName: "Segment",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Urgent",
            
        },
        {
            id: 1,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-2.png",
            job: "Recruiting Coordinator",
            companyName: "Catalyst",
            location: "London, UK",
            time: "Full Time",
            jobcategory: "Urgent",
        },
        {
            id: 2,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-3.png",
            job: "Product Manager, Studio",
            companyName: "Invision",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Urgent",
        },
        {
            id: 3,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-4.png",
            job: "Senior Product Designer",
            companyName: "Upwork",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Urgent",
        },
        {
            id: 4,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-5.png",
            job: "Product Manager, Risk",
            companyName: "Medium",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Private",
        },
        {
            id: 41,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-6.png",
            job: "Technical Architect",
            companyName: "lively",
            location: "London, UK",
            time: "Full Time",
            jobcategory: "Private",
        },
        {
            id: 42,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-7.png",
            job: "Web Developer",
            companyName: "Udemy",
            location: "London, UK",
            time: "Part Time",
            jobcategory: "Urgent",
        },
        {
            id: 43,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-8.png",
            job: "Senior Product Designer",
            companyName: "Twilio",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Private",
        },
        {
            id: 44,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-9.png",
            job: "Senior BI Analyst",
            companyName: "Figma",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Private",
        },
    ],
    "Trending": [
        {
            id: 1,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-2.png",
            job: "Recruiting Coordinator",
            companyName: "Catalyst",
            location: "London, UK",
            time: "Full Time",
            jobcategory: "Urgent",
        },
        {
            id: 41,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-6.png",
            job: "Technical Architect",
            companyName: "lively",
            location: "London, UK",
            time: "Full Time",
            jobcategory: "Private",
        },
        {
            id: 4,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-5.png",
            job: "Product Manager, Risk",
            companyName: "Medium",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Private",
        },
        {
            id: 2,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-3.png",
            job: "Product Manager, Studio",
            companyName: "Invision",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Urgent",
        },
        {
            id: 3,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-4.png",
            job: "Senior Product Designer",
            companyName: "Upwork",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Urgent",
        },
        {
            id: 6,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-1.png",
            job: "Software Engineer",
            companyName: "Segment",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Urgent",
        },
    ],
    "Design": [
        {
            id: 6,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-1.png",
            job: "Software Engineer",
            companyName: "Segment",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Urgent",
        },
        {
            id: 4,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-5.png",
            job: "Product Manager, Risk",
            companyName: "Medium",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Private",
        },
        {
            id: 3,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-4.png",
            job: "Senior Product Designer",
            companyName: "Upwork",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Urgent",
        },
        {
            id: 2,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-3.png",
            job: "Product Manager, Studio",
            companyName: "Invision",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Urgent",
        },
        {
            id: 41,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-6.png",
            job: "Technical Architect",
            companyName: "lively",
            location: "London, UK",
            time: "Full Time",
            jobcategory: "Private",
        },
        {
            id: 1,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-2.png",
            job: "Recruiting Coordinator",
            companyName: "Catalyst",
            location: "London, UK",
            time: "Full Time",
            jobcategory: "Urgent",
        },
    ],
    "Marketing": [
        {
            id: 42,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-7.png",
            job: "Web Developer",
            companyName: "Udemy",
            location: "London, UK",
            time: "Part Time",
            jobcategory: "Urgent",
        },
        {
            id: 43,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-8.png",
            job: "Senior Product Designer",
            companyName: "Twilio",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Private",
        },
        {
            id: 44,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-9.png",
            job: "Senior BI Analyst",
            companyName: "Figma",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Private",
        },
    ],
    "Health": [
        {
            id: 4,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-5.png",
            job: "Product Manager, Risk",
            companyName: "Medium",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Private",
        },
        {
            id: 2,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-3.png",
            job: "Product Manager, Studio",
            companyName: "Invision",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Urgent",
        },
        {
            id: 3,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-4.png",
            job: "Senior Product Designer",
            companyName: "Upwork",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Urgent",
        },
        {
            id: 6,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-1.png",
            job: "Software Engineer",
            companyName: "Segment",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Urgent",
        },
        {
            id: 43,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-8.png",
            job: "Senior Product Designer",
            companyName: "Twilio",
            location: "London, UK",
            time: "Temporary",
            jobcategory: "Private",
        },
        {
            id: 41,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-6.png",
            job: "Technical Architect",
            companyName: "lively",
            location: "London, UK",
            time: "Full Time",
            jobcategory: "Private",
        },
        {
            id: 42,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-7.png",
            job: "Web Developer",
            companyName: "Udemy",
            location: "London, UK",
            time: "Part Time",
            jobcategory: "Urgent",
        },
        {
            id: 44,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-9.png",
            job: "Senior BI Analyst",
            companyName: "Figma",
            location: "London, UK",
            time: "Freelancer",
            jobcategory: "Private",
        },
        {
            id: 1,
            image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-2.png",
            job: "Recruiting Coordinator",
            companyName: "Catalyst",
            location: "London, UK",
            time: "Full Time",
            jobcategory: "Urgent",
        },
    ]
}