export const dataOfFindJobs = [
    {
        id: 1,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-1.png",
        companyName: "Segment",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        jobType: "Full Time",
        experience: "1 Year",
    },
    {
        id: 2,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-2.png",
        companyName: "Catalyst",
        job: "Recruiting Coordinator",
        category: "Private",
        time: "Urgent",
        jobType: "Freelancer",
        experience: "3 Year",
    },
    {
        id: 3,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-4.png",
        companyName: "Upwork",
        job: "Senior Product Designer",
        category: "Private",
        time: "Urgent",
        jobType: "Temporary",
        experience: "Fresher",
    },
    {
        id: 4,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-5.png",
        companyName: "Medium",
        job: "Senior Stack Engineer, Creator Success",
        category: "Private",
        time: "Urgent",
        jobType: "Full Time",
        experience: "4 Year",
    },
    {
        id: 5,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-6.png",
        companyName: "Figma",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        jobType: "Freelancer",
        experience: "Fresher",
    },
    {
        id: 6,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-1.png",
        companyName: "Segment",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        jobType: "Part Time",
        experience: "1 Year",
    },
    {
        id: 7,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-2.png",
        companyName: "Catalyst",
        job: "Recruiting Coordinator",
        category: "Private",
        // time: "Urgent",
        jobType: "Temporary",
        experience: "4 Year",
    },
    {
        id: 8,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-3.png",
        companyName: "Invision",
        job: "Product Manager, Studio",
        // category: "Private",
        time: "Urgent",
        jobType: "Full Time",
        experience: "3 Year",
    },
    {
        id: 9,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-6.png",
        companyName: "Figma",
        job: "Web Developer",
        category: "Private",
        // time: "Urgent",
        jobType: "Part Time",
        experience: "2 Year",
    },
    {
        id: 10,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/1-4.png",
        companyName: "Upwork",
        job: "Senior Product Designer",
        // category: "Private",
        // time: "Urgent",
        jobType: "Temporary",
        experience: "Fresher",
    },
    {
        id: 11,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-1.png",
        companyName: "Segment",
        job: "Software Engineer",
        // category: "Private",
        time: "Urgent",
        jobType: "Freelancer",
        experience: "1 Year",
    },
    {
        id: 12,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-2.png",
        companyName: "Catalyst",
        job: "Recruiting Coordinator",
        category: "Private",
        time: "Urgent",
        jobType: "Full Time",
        experience: "2 Year",
    },
    {
        id: 13,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-3.png",
        companyName: "Invision",
        job: "Product Manager, Studio",
        category: "Public",
        time: "Urgent",
        jobType: "Part Time",
        experience: "3 Year",
    },
    {
        id: 14,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-4.png",
        companyName: "Upwork",
        job: "Senior Product Designer",
        category: "Public",
        // time: "Urgent",
        jobType: "Temporary",
        experience: "4 Year",
    },
    {
        id: 15,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-5.png",
        companyName: "Medium",
        job: "Product Manager, Risk",
        category: "Private",
        time: "Urgent",
        jobType: "Freelancer",
        experience: "Fresher",
    },
    {
        id: 16,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-6.png",
        companyName: "lively",
        job: "Technical Architect",
        category: "Private",
        // time: "Urgent",
        jobType: "Full Time",
        experience: "4 Year",
    },
    {
        id: 17,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-7.png",
        companyName: "Udemy",
        job: "Web Developer",
        // category: "Private",
        time: "Urgent",
        jobType: "Part Time",
        experience: "2 Year",
    },
    {
        id: 18,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-8.png",
        companyName: "Twilio",
        job: "Senior Product Designer",
        category: "Private",
        time: "Urgent",
        jobType: "Temporary",
        experience: "Fresher",
    },
    {
        id: 19,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/2-9.png",
        companyName: "Figma",
        job: "Senior BI Analyst",
        category: "Private",
        time: "Urgent",
        jobType: "Freelancer",
        experience: "2 Year",
    },
    {
        id: 20,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-1.png",
        companyName: "Segment",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        // jobType: "Full Time",
        experience: "Fresher",
    },
    {
        id: 21,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-2.png",
        companyName: "Catalyst",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        jobType: "Part Time",
        experience: "3 Year",
    },
    {
        id: 22,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-3.png",
        companyName: "Invision",
        job: "Lead Software Engineer",
        category: "Public",
        time: "Urgent",
        jobType: "Temporary",
        experience: "4 Year",
    },
    {
        id: 23,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-4.png",
        companyName: "Upwork",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        jobType: "Freelancer",
        experience: "3 Year",
    },
    {
        id: 24,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-5.png",
        companyName: "Medium",
        job: "Siniour Web Developer",
        category: "Public",
        time: "Urgent",
        jobType: "Full Time",
        experience: "Fresher",
    },
    {
        id: 25,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-6.png",
        companyName: "Figma",
        job: "Senior BI Analyst",
        category: "Private",
        time: "Urgent",
        jobType: "Part Time",
        experience: "1 Year",
    },
    {
        id: 26,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-7.png",
        companyName: "Spectrap",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        jobType: "Temporary",
        experience: "1 Year",
    },
    {
        id: 27,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-8.png",
        companyName: "Dropbox",
        job: "Senior BI Analyst",
        category: "Public",
        time: "Urgent",
        jobType: "Freelancer",
        experience: "Fresher",
    },
    {
        id: 28,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-1.png",
        companyName: "Segment",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        jobType: "Full Time",
        experience: "1 Year",
    },
    {
        id: 29,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-2.png",
        companyName: "Catalyst",
        job: "Software Engineer (Android), Libraries",
        category: "Public",
        time: "Urgent",
        jobType: "Part Time",
        experience: "1 Year",
    },
    {
        id: 30,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-3.png",
        companyName: "Invision",
        job: "Lead Software Engineer",
        category: "Private",
        time: "Urgent",
        jobType: "Temporary",
        experience: "1 Year",
    },
    {
        id: 31,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-4.png",
        companyName: "Upwork",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        jobType: "Freelancer",
        experience: "Fresher",
    },
    {
        id: 32,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-5.png",
        companyName: "Medium",
        job: "Siniour Web Developer",
        category: "Private",
        time: "Urgent",
        jobType: "Full Time",
        experience: "4 Year",
    },
    {
        id: 33,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-1.png",
        companyName: "Segment",
        job: "Software Engineer (Android), Libraries",
        category: "Public",
        time: "Urgent",
        jobType: "Full Time",
        experience: "3 Year",
    },
    {
        id: 34,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-2.png",
        companyName: "Catalyst",
        job: "Senior Full Stack, Creator Success",
        category: "Private",
        time: "Urgent",
        jobType: "Part Time",
        experience: "Fresher",
    },
    {
        id: 35,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/3-3.png",
        companyName: "invision",
        job: "Software Engineer (Android), Libraries",
        category: "Private",
        time: "Urgent",
        jobType: "Full Time",
        experience: "Fresher",
    },
    
    
]