export const dataOfEmployers = [
    {
        id: 1,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-1.png",
        companyName: "Udemy",
        category: "Resedential",
        jobsAvailable: "15",
    },
    {
        id: 2,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-2.png",
        companyName: "Stripe",
        category: "Commercial",
        jobsAvailable: "22",
        
    },
    {
        id: 3,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-3.png",
        companyName: "Dropbox",
        category: "Apartments",
        jobsAvailable: "25",
    },
    {
        id: 4,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/6-3.png",
        companyName: "Checkr",
        category: "Industrial",
        jobsAvailable: "11",
    },
    {
        id: 5,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/6-4.png",
        companyName: "Mural",
        category: "Residential",
        jobsAvailable: "3",
    },
    {
        id: 6,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-6.png",
        companyName: "Stripe",
        category: "Commercial",
        jobsAvailable: "22",
    },
    {
        id: 7,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-3.png",
        companyName: "Dropbox",
        category: "Apartments",
        jobsAvailable: "22",
    },
    {
        id: 8,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-4.png",
        companyName: "Figma",
        category: "Industrial",
        jobsAvailable: "25",
    },
    {
        id: 9,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/6-2.png",
        companyName: "Opendoor",
        category: "Residential",
        jobsAvailable: "12",
    },
    {
        id: 10,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-2.png",
        companyName: "Stripe",
        category: "Commercial",
        jobsAvailable: "22",
    },
    {
        id: 11,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-3.png",
        companyName: "Dropbox",
        category: "Apartments",
        jobsAvailable: "25",
    },
    {
        id: 12,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-4.png",
        companyName: "Figma",
        category: "Resedential",
        jobsAvailable: "25",
    },
    {
        id: 13,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/6-1.png",
        companyName: "Netflix",
        category: "Commercial",
        featured: "Yes",
        jobsAvailable: "5",
    },
    {
        id: 14,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/6-5.png",
        companyName: "Astronomer",
        category: "Industrial",
        featured: "Yes",
        jobsAvailable: " 8",
    },
    {
        id: 15,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/6-1.png",
        companyName: "Figma",
        category: "Industrial",
        jobsAvailable: "25",
    },
    {
        id: 16,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/6-2.png",
        companyName: "Opendoor",
        category: "Residential",
        jobsAvailable: "12",
    },
    {
        id: 17,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-2.png",
        companyName: "Stripe",
        category: "Commercial",
        jobsAvailable: "22",
    },
    {
        id: 18,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/6-3.png",
        companyName: "Checkr",
        category: "Industrial",
        jobsAvailable: "11",
    },
    {
        id: 19,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-logo/6-1.png",
        companyName: "Netflix",
        category: "Commercial",
        featured: "Yes",
        jobsAvailable: "5",
    },
    {
        id: 20,
        image: "https://superio-reactjs.ibthemespro.com/images/resource/company-3.png",
        companyName: "Dropbox",
        category: "Apartments",
        jobsAvailable: "22",
    },
    
    
    
]